# The source and target fields should follow the ISO 639 format, e.g. ko, ja,
# zh-CN, zh-TW. All available language codes can be found in the lang.go file:
#
#   https://github.com/souk4711/honyakusha/blob/main/internal/lang/lang.go
#
# Note: some language codes may not work if the translation services do not support them.
[translate]
source = ""
target = "ja"

[translators.bing]
enabled = true
# uri = "https://www.bing.com"
# proxy = ""

[translators.google]
enabled = true
# uri = "https://translate.google.com"
# proxy = ""

[translators.deepl-api]
enabled = false
# uri = "https://api-free.deepl.com"
# proxy = ""
# api-key = ""

[translators.libretranslate-api]
enabled = false
# uri = "https://libretranslate.com"
# proxy = ""
# api-key = ""
