[translate]
source = ""
target = "en-US"

[translators.bing]
enabled = true
# uri = "https://www.bing.com"
# proxy = ""

[translators.google]
enabled = true
# uri = "https://translate.google.com"
# proxy = ""

[translators.libretranslate-api]
enabled = false
# uri = "https://libretranslate.com"
# proxy = ""
# api-key = ""
