name: Lints

on: [push, pull_request]

jobs:
  test:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Set up golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
      - run: golangci-lint run
